# @url = https://eaf31510-b759-4e3e-ae9f-7476383f4078-00-1re1y04gi1054.kirk.replit.dev
@url = http://127.0.0.1:8000
#####
GET {{url}}/ping?message=oi
Api-Key: teste123
Content-Type: application/json

{

}

#####
POST {{url}}/profile/user/create
Api-Key: teste123
Content-Type: application/json

{
    "name": "Test Delete",
    "country": "USA",
    "email": "alice2@example.com"
}

#####
GET {{url}}/profile/user/a618c407-d897-408f-b89c-fc01eb5e31b6
Api-Key: teste123
Content-Type: application/json

{

}
#####
PUT {{url}}/profile/user/f91eed13-bb74-4863-af56-dd779040464b
Api-Key: teste123
Content-Type: application/json

{
    "name": "Alice Muniz",
    "country": "USA",
    "email": "alice@example.com"
}

#####
DELETE  {{url}}/profile/user/a618c407-d897-408f-b89c-fc01eb5e31b6
Api-Key: teste123
Content-Type: application/json

{

}

#####
POST {{url}}/journey/list
Api-Key: teste123
Content-Type: application/json

#####
POST {{url}}/journey/activities
Api-Key: teste123
Content-Type: application/json

{
    "uuid": "867681a7-2267-4c85-8b08-53b1446f9e58"
}
#####
POST {{url}}/journey/quiz
Api-Key: teste123
Content-Type: application/json

{
    "uuid": "867681a7-2267-4c85-8b08-53b1446f9e58"
}
#####
POST {{url}}/profiles/docs
Api-Key: teste123
Content-Type: application/json

{
    "name": "John",
    "country": "Brazil",
    "email": "john@example.com"
}
#####
GET {{url}}/docs
Api-Key: teste123
Content-Type: application/json

{
    "name": "John",
    "country": "Brazil",
    "email": "john@example.com"
}
